apiVersion: v1
kind: Service
metadata:
  name: opamp-control-plane
  namespace: opamp-system
  labels:
    app.kubernetes.io/name: opamp-control-plane
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: opamp
      port: 4320
      targetPort: opamp
      protocol: TCP
  selector:
    app.kubernetes.io/name: opamp-control-plane
